# Generated by Django 5.1 on 2024-08-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMPData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, null=True)),
                ('press', models.FloatField(blank=True, null=True)),
                ('falha', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sht_ativo', models.BooleanField(blank=True, null=True)),
                ('bmp_ativo', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SHTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, null=True)),
                ('umid', models.FloatField(blank=True, null=True)),
                ('falha', models.BooleanField(blank=True, null=True)),
                ('a_temp', models.BooleanField(blank=True, null=True)),
                ('a_umid', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='payload',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='bmp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SensorData.bmpdata'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SensorData.devicedata'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sht',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SensorData.shtdata'),
        ),
    ]
