# Generated by Django 5.1 on 2024-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorData', '0004_alter_bmpdata_press_alter_bmpdata_temp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceData',
            new_name='Devices',
        ),
        migrations.AddField(
            model_name='bmpdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shtdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
