# Generated by Django 5.1 on 2024-08-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SensorData', '0005_rename_devicedata_devices_bmpdata_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='Device',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
