# Generated by Django 5.1 on 2024-08-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SensorData', '0006_rename_devices_device_delete_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmpdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmp_data', to='SensorData.device'),
        ),
        migrations.AddField(
            model_name='shtdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sht_data', to='SensorData.device'),
        ),
    ]
