# Generated by Django 5.1 on 2024-08-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SensorData', '0007_bmpdata_device_shtdata_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmpdata',
            options={'verbose_name': '3 - Dados do Sensor BMP', 'verbose_name_plural': '3 - Dados dos Sensores BMP'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '1 - Dispositivo', 'verbose_name_plural': '1 - Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='shtdata',
            options={'verbose_name': '2 - Dados do Sensor SHT', 'verbose_name_plural': '2 - Dados dos Sensores SHT'},
        ),
    ]
